# Generated by Django 4.2.11 on 2024-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
