# Generated by Django 4.2.11 on 2024-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('reminder', 'Reminder')], default='message', max_length=10),
        ),
    ]
