# Generated by Django 4.2.11 on 2024-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
