# Generated by Django 4.2.11 on 2024-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('FILE', 'File'), ('URL', 'URL')], default='OTHER', max_length=10),
        ),
    ]
